import { type LucideIcon } from 'lucide-react';
import {
  AlertCircle,
  ArrowRight,
  Bell,
  BookOpen,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Circle,
  Clock,
  Code2,
  Copy,
  CreditCard,
  Database,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Github,
  GraduationCap,
  Grid,
  HelpCircle,
  Home,
  Image,
  Info,
  Laptop,
  LayoutDashboard,
  LineChart,
  Link as LinkIcon,
  List,
  Loader2,
  LogOut,
  Mail,
  MailCheck,
  Menu,
  MessageSquare,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Plus,
  PlusCircle,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Star,
  Sun,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  X,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  logo: Code2,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  trash: Trash2,
  settings: Settings,
  user: User,
  users: Users,
  plus: Plus,
  plusCircle: PlusCircle,
  home: Home,
  dashboard: LayoutDashboard,
  menu: Menu,
  lineChart: LineChart,
  search: Search,
  check: Check,
  checkCircle: CheckCircle2,
  arrowRight: ArrowRight,
  bookOpen: BookOpen,
  info: Info,
  link: LinkIcon,
  logout: LogOut,
  mail: Mail,
  mailCheck: MailCheck,
  github: Github,
  star: Star,
  helpCircle: HelpCircle,
  download: Download,
  alertCircle: AlertCircle,
  eye: Eye,
  eyeOff: EyeOff,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  grid: Grid,
  clock: Clock,
  copy: Copy,
  calendar: Calendar,
  filter: Filter,
  chevronDown: ChevronDown,
  circle: Circle,
  send: Send,
  messageSquare: MessageSquare,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  creditCard: CreditCard,
  share2: Share2,
  upload: Upload,
  database: Database,
  image: Image,
  minus: Minus,
  trendingUp: TrendingUp,
  refreshCw: RefreshCw,
  fileText: FileText,
  list: List,
  edit: Edit,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  externalLink: ExternalLink,
  slidersHorizontal: SlidersHorizontal,
  save: Save,
  graduationCap: GraduationCap,
  bell: Bell,
} as const;

export type IconName = keyof typeof Icons;
