"use client";

import React, { useState, useEffect } from "react";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ChangeRequestForm } from "@/components/committee/teaching-load/ChangeRequestForm";
import { ChangeRequestsList } from "@/components/committee/teaching-load/ChangeRequestsList";
import { WorkloadAnalyticsChart } from "@/components/committee/teaching-load/WorkloadAnalyticsChart";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Info } from "lucide-react";

interface TeachingLoadDashboardPageClientProps {
  displayName: string;
}

export default function TeachingLoadDashboardPageClient({
  displayName,
}: TeachingLoadDashboardPageClientProps) {
  const [showRequestForm, setShowRequestForm] = useState(false);
  const [selectedSection, setSelectedSection] = useState<any>(null);
  const [scheduleVersionId, setScheduleVersionId] = useState<string | null>(null);
  const [workloadData, setWorkloadData] = useState<any[]>([]);

  useEffect(() => {
    // TODO: Fetch latest schedule version and workload data
    // This would come from an API endpoint that provides:
    // 1. Latest schedule version ID
    // 2. Faculty workload statistics
    
    // For now, we'll show placeholder message
    fetchScheduleData();
  }, []);

  const fetchScheduleData = async () => {
    // TODO: Implement API call to fetch schedule version and workload data
    // Example:
    // const response = await fetch('/api/committee/teaching-load/current-schedule');
    // const data = await response.json();
    // setScheduleVersionId(data.scheduleVersionId);
    // setWorkloadData(data.workloadData);
  };

  const handleOpenRequestForm = () => {
    // For demo purposes, we'll set a mock section
    // In production, this would be selected from the schedule view
    setSelectedSection({
      section_id: 'DEMO-SECTION-01',
      course_code: 'SWE301',
      section_number: '01',
      current_instructor: 'faculty-001',
      current_capacity: 40,
      current_room: 'B204',
    });
    setShowRequestForm(true);
  };

  return (
    <div className="container mx-auto max-w-7xl px-4 py-12 space-y-8">
      <header className="space-y-2">
        <h1 className="text-3xl font-bold tracking-tight">
          Teaching Load Committee Dashboard
        </h1>
        <p className="text-muted-foreground">
          Monitor workload distribution and submit change requests for schedule refinements.
        </p>
        <p className="text-sm text-muted-foreground">
          Signed in as {displayName}
        </p>
      </header>

      {/* Info Alert */}
      <Alert>
        <Info className="h-4 w-4" />
        <AlertDescription>
          This dashboard allows you to review faculty workload distribution and submit change requests.
          Once a schedule version is generated by the scheduling committee, you can propose adjustments
          that will be validated against irregular student requirements.
        </AlertDescription>
      </Alert>

      {/* Quick Actions */}
      <Card>
        <CardHeader>
          <CardTitle>Quick Actions</CardTitle>
          <CardDescription>
            Submit change requests and review pending proposals
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex gap-4">
            <Button onClick={handleOpenRequestForm}>
              <Plus className="mr-2 h-4 w-4" />
              New Change Request
            </Button>
            <Button variant="outline" disabled>
              View Schedule
            </Button>
          </div>
          <p className="text-xs text-muted-foreground mt-4">
            Note: Full schedule view and section selection coming soon. For now, use the demo section for testing.
          </p>
        </CardContent>
      </Card>

      {/* Workload Analytics */}
      <WorkloadAnalyticsChart 
        workloadData={workloadData}
        standardLoad={12}
      />

      {/* Change Requests List */}
      <ChangeRequestsList 
        scheduleVersionId={scheduleVersionId || undefined}
        userRole="teaching_load"
      />

      {/* Change Request Form Dialog */}
      {selectedSection && (
        <ChangeRequestForm
          open={showRequestForm}
          onClose={() => setShowRequestForm(false)}
          sectionId={selectedSection.section_id}
          sectionDetails={selectedSection}
          scheduleVersionId={scheduleVersionId || 'demo-version-01'}
          onSuccess={() => {
            // Refresh the change requests list
            window.location.reload();
          }}
        />
      )}
    </div>
  );
}
