// Student Schedule View - Production Page
"use client";

import React, { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/auth/use-auth";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Loader2, ArrowLeft, Calendar } from "lucide-react";
import Link from "next/link";

export default function StudentSchedulePage() {
  const router = useRouter();
  const { user, isLoading: authLoading } = useAuth();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!authLoading) {
      if (!user) {
        router.push("/");
      } else {
        setLoading(false);
      }
    }
  }, [user, authLoading, router]);

  if (authLoading || loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <Loader2 className="h-8 w-8 animate-spin mx-auto mb-4 text-primary" />
          <p className="text-muted-foreground">Loading...</p>
        </div>
      </div>
    );
  }

  // Mock schedule data - replace with actual API call
  const hasSchedule = false;

  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      {/* Header */}
      <div className="mb-8">
        <Link href="/student">
          <Button variant="ghost" size="sm" className="mb-4">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Dashboard
          </Button>
        </Link>
        <h1 className="text-3xl font-bold mb-2">My Schedule</h1>
        <p className="text-muted-foreground">
          View your course schedule and exam dates
        </p>
      </div>

      {/* Content */}
      {!hasSchedule ? (
        <Card>
          <CardContent className="pt-6">
            <div className="text-center py-12">
              <Calendar className="h-16 w-16 mx-auto mb-4 text-muted-foreground" />
              <h3 className="text-xl font-semibold mb-2">
                Schedule Not Available
              </h3>
              <p className="text-muted-foreground mb-6 max-w-md mx-auto">
                Your schedule will be available after elective preferences are
                processed and the final schedule is generated by the scheduling
                committee.
              </p>
              <Button asChild>
                <Link href="/student/electives">
                  Submit Elective Preferences
                </Link>
              </Button>
            </div>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-6">
          {/* Schedule Grid */}
          <Card>
            <CardHeader>
              <CardTitle>Weekly Schedule</CardTitle>
              <CardDescription>Spring 2025 Semester</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                Schedule grid will appear here
              </p>
            </CardContent>
          </Card>

          {/* Exam Schedule */}
          <Card>
            <CardHeader>
              <CardTitle>Exam Schedule</CardTitle>
              <CardDescription>Midterms and Finals</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                Exam dates will appear here
              </p>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
}
