// Student Schedule View - Production Page
"use client";

import React, { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/auth/use-auth";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Empty,
  EmptyHeader,
  EmptyTitle,
  EmptyDescription,
  EmptyMedia,
} from "@/components/ui/empty";
import { ArrowLeft, Calendar } from "lucide-react";
import Link from "next/link";

export default function StudentSchedulePage() {
  const router = useRouter();
  const { user, isLoading: authLoading } = useAuth();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!authLoading) {
      if (!user) {
        router.push("/");
      } else {
        setLoading(false);
      }
    }
  }, [user, authLoading, router]);

  if (authLoading || loading) {
    return (
      <div className="container mx-auto px-4 py-8 max-w-7xl">
        <div className="mb-8">
          <Skeleton className="h-10 w-40 mb-4" />
          <Skeleton className="h-9 w-64 mb-2" />
          <Skeleton className="h-5 w-80" />
        </div>

        <div className="space-y-6">
          <Card>
            <CardHeader>
              <Skeleton className="h-6 w-48 mb-2" />
              <Skeleton className="h-4 w-32" />
            </CardHeader>
            <CardContent>
              <Skeleton className="h-96 w-full" />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <Skeleton className="h-6 w-40 mb-2" />
              <Skeleton className="h-4 w-48" />
            </CardHeader>
            <CardContent>
              <Skeleton className="h-64 w-full" />
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  // Mock schedule data - replace with actual API call
  const hasSchedule = false;

  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      {/* Header */}
      <div className="mb-8">
        <Link href="/student">
          <Button variant="ghost" size="sm" className="mb-4">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Dashboard
          </Button>
        </Link>
        <h1 className="text-3xl font-bold mb-2">My Schedule</h1>
        <p className="text-muted-foreground">
          View your course schedule and exam dates
        </p>
      </div>

      {/* Content */}
      {!hasSchedule ? (
        <Empty className="min-h-[500px]">
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <Calendar className="h-8 w-8" />
            </EmptyMedia>
            <EmptyTitle>Schedule Not Available</EmptyTitle>
            <EmptyDescription>
              Your schedule will be available after elective preferences are
              processed and the final schedule is generated by the scheduling
              committee.
            </EmptyDescription>
          </EmptyHeader>
          <Button asChild size="lg">
            <Link href="/student/electives">Submit Elective Preferences</Link>
          </Button>
        </Empty>
      ) : (
        <div className="space-y-6">
          {/* Schedule Grid */}
          <Card>
            <CardHeader>
              <CardTitle>Weekly Schedule</CardTitle>
              <CardDescription>Spring 2025 Semester</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                Schedule grid will appear here
              </p>
            </CardContent>
          </Card>

          {/* Exam Schedule */}
          <Card>
            <CardHeader>
              <CardTitle>Exam Schedule</CardTitle>
              <CardDescription>Midterms and Finals</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                Exam dates will appear here
              </p>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
}
