// Student Schedule View - Production Page
"use client";

import React, { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/auth/use-auth";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Empty,
  EmptyHeader,
  EmptyTitle,
  EmptyDescription,
  EmptyMedia,
} from "@/components/ui/empty";
import { ArrowLeft, Calendar } from "lucide-react";
import Link from "next/link";

export default function StudentSchedulePage() {
  const router = useRouter();
  const { user, isLoading: authLoading } = useAuth();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!authLoading) {
      if (!user) {
        router.push("/");
      } else {
        setLoading(false);
      }
    }
  }, [user, authLoading, router]);

  if (authLoading || loading) {
    return (
      <div className="container mx-auto px-4 py-8 max-w-7xl">
        <div className="mb-8">
          <Skeleton className="h-10 w-40 mb-4" />
          <Skeleton className="h-9 w-64 mb-2" />
          <Skeleton className="h-5 w-80" />
        </div>

        <div className="space-y-6">
          <Card>
            <CardHeader>
              <Skeleton className="h-6 w-48 mb-2" />
              <Skeleton className="h-4 w-32" />
            </CardHeader>
            <CardContent>
              <Skeleton className="h-96 w-full" />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <Skeleton className="h-6 w-40 mb-2" />
              <Skeleton className="h-4 w-48" />
            </CardHeader>
            <CardContent>
              <Skeleton className="h-64 w-full" />
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  // Mock schedule data - replace with actual API call
  const hasSchedule = false;

  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      {/* Header */}
      <div className="mb-8">
        <Link href="/student/dashboard">
          <Button variant="ghost" size="sm" className="mb-4">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Dashboard
          </Button>
        </Link>
        <h1 className="text-3xl font-bold mb-2">My Schedule</h1>
        <p className="text-muted-foreground">
          View your course schedule and exam dates
        </p>
      </div>

      {/* Content */}
      {loading ? (
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <Skeleton className="h-6 w-48 mb-2" />
              <Skeleton className="h-4 w-32" />
            </CardHeader>
            <CardContent>
              <Skeleton className="h-96 w-full" />
            </CardContent>
          </Card>
        </div>
      ) : !hasSchedule ? (
        <Empty className="min-h-[500px]">
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <Calendar className="h-8 w-8" />
            </EmptyMedia>
            <EmptyTitle>Schedule Not Available</EmptyTitle>
            <EmptyDescription>
              Your schedule will be available after elective preferences are
              processed and the final schedule is generated by the scheduling
              committee.
            </EmptyDescription>
          </EmptyHeader>
          <Button asChild size="lg">
            <Link href="/student/electives">Submit Elective Preferences</Link>
          </Button>
        </Empty>
      ) : (
        <div className="space-y-6">
          {/* Schedule Grid */}
          <Card>
            <CardHeader>
              <CardTitle>Weekly Schedule</CardTitle>
              <CardDescription>{scheduleData.term}</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {scheduleData.courses.map((course: any) => (
                  <div key={course.courseCode} className="border rounded-lg p-4">
                    <div className="flex items-start justify-between mb-3">
                      <div>
                        <h3 className="font-semibold">
                          {course.courseCode} - {course.courseName}
                        </h3>
                        <p className="text-sm text-muted-foreground">
                          {course.instructor} • Section {course.section} • {course.credits} credits
                        </p>
                      </div>
                    </div>
                    <div className="grid gap-2">
                      {course.schedule.map((slot: any, idx: number) => (
                        <div
                          key={idx}
                          className="flex items-center gap-2 text-sm bg-muted/50 rounded p-2"
                        >
                          <span className="font-medium w-24">{slot.day}</span>
                          <span className="text-muted-foreground">
                            {slot.startTime} - {slot.endTime}
                          </span>
                          <span className="text-muted-foreground">•</span>
                          <span className="text-muted-foreground">{slot.room}</span>
                          <span className="ml-auto text-xs font-medium px-2 py-1 bg-primary/10 text-primary rounded">
                            {slot.type}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Course Summary */}
          <Card>
            <CardHeader>
              <CardTitle>Course Summary</CardTitle>
              <CardDescription>
                Total credits: {scheduleData.courses.reduce((sum, c) => sum + c.credits, 0)}
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="text-sm text-muted-foreground">
                You are enrolled in {scheduleData.courses.length} courses this term.
              </div>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
}
